from __future__ import annotations

import html
import json


def render_page(title: str, version: str) -> str:
    safe_title = html.escape(title)
    title_json = json.dumps(title)
    version_json = json.dumps(version)
    page = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#080a0d">
<title>__SAFE_TITLE__</title>
<style>
:root{color-scheme:dark;--bg:#080a0d;--panel:#171a1f;--panel2:#22262d;--panel3:#101317;--text:#f5f7fb;--muted:#aeb6c2;--blue:#347ff0;--blue2:#184c91;--green:#16a261;--green2:#0d5d38;--red:#d74a52;--amber:#e2a438;--border:#2d333d;--shadow:0 16px 38px rgba(0,0,0,.32)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 50% -20%,#172132 0,#080a0d 40%);color:var(--text);font-family:Inter,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif}button,input{font:inherit}button{border:0;cursor:pointer}button:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid #79aaff;outline-offset:2px}
main{width:min(1180px,100%);margin:auto;padding:18px}.topbar{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:4px 4px 18px}.brand{display:flex;align-items:center;gap:13px}.logo{font-size:40px}.brand h1{font-size:clamp(27px,4vw,42px);line-height:1;margin:0}.brand small{font-size:.58em;color:#dce4ef}
.panel{background:rgba(23,26,31,.96);border:1px solid var(--border);border-radius:22px;padding:18px;margin:13px 0;box-shadow:var(--shadow)}.statusbar{display:flex;flex-wrap:wrap;gap:9px}.pill{display:inline-flex;align-items:center;gap:7px;border-radius:999px;padding:9px 13px;background:var(--panel2);font-size:13px;color:#e8edf5}.pill.online{background:var(--green2)}.pill.offline{background:#79232a}.pill.warn{background:#74500d}.pulse{width:8px;height:8px;border-radius:50%;background:currentColor;opacity:.9}
.overview{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px}.stat{background:var(--panel2);border:1px solid #2b3038;border-radius:17px;padding:16px;min-height:94px}.stat strong{display:block;font-size:clamp(22px,3vw,30px);overflow-wrap:anywhere}.stat span{color:var(--muted);font-size:13px}
.chat-panel{padding:0;overflow:hidden}.chat-head{display:flex;justify-content:space-between;align-items:center;padding:15px 18px;border-bottom:1px solid var(--border)}.chat-head h2{font-size:17px;margin:0}.chat-head-actions{display:flex;gap:8px}.ghost{background:var(--panel2);color:var(--text);border-radius:11px;padding:8px 11px;font-size:13px}
.chat{display:flex;flex-direction:column;gap:14px;min-height:260px;max-height:58vh;overflow:auto;padding:18px;scrollbar-gutter:stable}.turn{display:flex;flex-direction:column;gap:6px}.turn.user{align-items:flex-end}.turn.assistant{align-items:stretch}.user-bubble{background:linear-gradient(135deg,var(--blue2),#17335a);padding:12px 15px;border-radius:18px 18px 5px 18px;max-width:min(80%,720px);overflow-wrap:anywhere}
.answer-card{background:var(--panel3);border:1px solid #245b3c;border-radius:18px;overflow:hidden}.answer-top{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:13px 15px;border-bottom:1px solid #26322c}.answer-title{font-weight:750}.answer-meta{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:6px}.route-badge{background:#213049;color:#dce9ff;border-radius:999px;padding:5px 9px;font-size:11px}.answer-body{padding:15px}.answer-text{white-space:pre-wrap;line-height:1.48;overflow-wrap:anywhere;color:#edf2f8}.rich-title{font-size:19px;font-weight:800;margin-bottom:2px}.rich-subtitle{color:var(--muted);font-size:13px;margin-bottom:13px}
.metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin:12px 0}.metric{background:#1b2026;border:1px solid #2c333d;border-radius:14px;padding:12px;min-width:0}.metric-icon{font-size:18px}.metric-value{font-size:20px;font-weight:800;overflow-wrap:anywhere}.metric-label{color:var(--muted);font-size:12px}.item-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:12px}.item{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px;background:#181c22;border:1px solid #2a3039;border-radius:13px;padding:11px;min-width:0}.item.warning{border-color:#72541b}.item.danger{border-color:#743239}.item.success{border-color:#235f40}.item-icon{font-size:20px}.item-main{min-width:0}.item-title{font-weight:700;overflow-wrap:anywhere}.item-subtitle{font-size:12px;color:var(--muted);overflow-wrap:anywhere}.item-value{font-weight:800;text-align:right;overflow-wrap:anywhere}
.note{margin-top:12px;color:var(--muted);font-size:12px}.answer-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}.mini{background:#252b34;color:#dce4ee;border-radius:9px;padding:6px 9px;font-size:12px}details.tech{margin-top:12px;border-top:1px solid #283039;padding-top:10px;color:var(--muted)}details.tech summary{cursor:pointer;font-size:12px}details.tech pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:240px;overflow:auto;background:#090b0e;padding:11px;border-radius:10px;font-size:11px;color:#cbd5e1}
.composer{border-top:1px solid var(--border);background:#14171c;padding:14px 16px;position:sticky;bottom:0}.inputrow{display:grid;grid-template-columns:1fr auto;gap:10px}.inputrow input{width:100%;min-width:0;padding:16px;border:1px solid #d5dbe3;border-radius:14px;background:#fff;color:#111;font-size:17px}.primary{background:var(--blue);color:white;border-radius:14px;padding:13px 21px}.primary:disabled{opacity:.55}.composer-tools{display:flex;gap:9px;margin-top:10px}.speak{flex:1;background:#176f3a;color:white;border-radius:13px;padding:12px}.toggle{background:var(--panel2);color:var(--text);border-radius:13px;padding:12px 14px}.toggle.active{background:#6a4b12}.working{display:none;align-items:center;gap:8px;color:var(--muted);font-size:12px;margin-top:9px}.working.show{display:flex}.spinner{width:14px;height:14px;border:2px solid #4a5260;border-top-color:#8ab5ff;border-radius:50%;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
.quick{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.quick button{background:var(--panel2);color:var(--text);border:1px solid #2b313a;border-radius:14px;min-height:61px;padding:11px}.quick button:hover{background:#2a3038}.footer{color:var(--muted);font-size:11px;text-align:center;padding:14px}
@media(max-width:820px){.overview,.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.quick{grid-template-columns:repeat(2,minmax(0,1fr))}.item-list{grid-template-columns:1fr}}@media(max-width:560px){main{padding:10px}.panel{border-radius:17px;padding:13px}.topbar{align-items:flex-start}.logo{font-size:32px}.brand h1{font-size:28px}.chat{padding:12px;max-height:56vh}.composer{padding:12px}.inputrow{grid-template-columns:1fr auto}.primary{padding:12px 15px}.user-bubble{max-width:90%}.answer-top{flex-direction:column}.answer-meta{justify-content:flex-start}.overview{gap:7px}.stat{padding:12px;min-height:82px}}
</style>
</head>
<body>
<main>
<header class="topbar"><div class="brand"><div class="logo">🏠</div><h1><span id="title"></span> <small id="version"></small></h1></div></header>
<section class="panel"><div class="statusbar"><span id="overall" class="pill warn"><i class="pulse"></i>Starting…</span><span id="mcp" class="pill">MCP unknown</span><span id="ollama" class="pill">Ollama unknown</span><span id="route" class="pill">Route: automatic</span></div></section>
<section class="panel"><div class="overview"><div class="stat"><strong id="tools">—</strong><span>MCP tools</span></div><div class="stat"><strong id="model">—</strong><span>Ollama model</span></div><div class="stat"><strong id="fallback">—</strong><span>Fallback</span></div><div class="stat"><strong id="lastRoute">—</strong><span>Last route</span></div></div></section>
<section class="panel chat-panel">
<div class="chat-head"><h2>Conversation</h2><div class="chat-head-actions"><button id="clear" class="ghost">Clear</button></div></div>
<div id="chat" class="chat"><div class="answer-card"><div class="answer-body"><div class="answer-text">Ready. Ask about your Hubitat devices, rooms, rules, or hub status.</div></div></div></div>
<div class="composer"><div class="inputrow"><input id="query" placeholder="Ask your Hubitat…" autocomplete="off"><button id="ask" class="primary">Ask</button></div><div class="composer-tools"><button id="speak" class="speak">🎤 Speak</button><button id="readToggle" class="toggle" title="Read responses aloud">🔇 Read answers</button></div><div id="working" class="working"><span class="spinner"></span><span id="workingText">Contacting Hubitat…</span></div></div>
</section>
<section class="panel"><div class="quick"><button data-q="What's happening at home?">🏠 What's happening?</button><button data-q="Which lights are on?">💡 Lights on</button><button data-q="Which batteries are low?">🪫 Low batteries</button><button data-q="Check the hub health status">🧠 Hub health</button><button data-q="List my Hubitat rooms">🚪 Rooms</button><button data-q="What is the weather?">🌦️ Weather</button><button data-q="List active automation rules">⚙️ Rules</button><button data-q="Find devices that need attention">⚠️ Attention</button></div></section>
<div class="footer">Powered by Ollama and kingpanther13's Hubitat MCP Rule Server. MCP is the live device-control source.</div>
</main>
<script>
const TITLE=__TITLE_JSON__,VERSION=__VERSION_JSON__;document.getElementById('title').textContent=TITLE;document.getElementById('version').textContent='v'+VERSION;
const chat=document.getElementById('chat'),input=document.getElementById('query'),ask=document.getElementById('ask'),working=document.getElementById('working'),workingText=document.getElementById('workingText');let history=JSON.parse(sessionStorage.getItem('hmcp_history')||'[]');let readAnswers=localStorage.getItem('hmcp_read_answers')==='true';
function save(){sessionStorage.setItem('hmcp_history',JSON.stringify(history.slice(-14)))}function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}function scrollChat(){requestAnimationFrame(()=>{chat.scrollTop=chat.scrollHeight})}function userTurn(text){const turn=el('div','turn user');turn.appendChild(el('div','user-bubble',text));chat.appendChild(turn);scrollChat()}
function metricGrid(metrics){if(!Array.isArray(metrics)||!metrics.length)return null;const grid=el('div','metric-grid');metrics.forEach(m=>{const card=el('div','metric');card.appendChild(el('div','metric-icon',m.icon||'•'));card.appendChild(el('div','metric-value',String(m.value??'—')));card.appendChild(el('div','metric-label',m.label||''));grid.appendChild(card)});return grid}function itemList(items){if(!Array.isArray(items)||!items.length)return null;const list=el('div','item-list');items.forEach(item=>{const row=el('div','item '+(item.tone||''));row.appendChild(el('div','item-icon',item.icon||'•'));const main=el('div','item-main');main.appendChild(el('div','item-title',item.title||''));if(item.subtitle)main.appendChild(el('div','item-subtitle',item.subtitle));row.appendChild(main);row.appendChild(el('div','item-value',String(item.value??'')));list.appendChild(row)});return list}
function speakText(text){if(!readAnswers||!window.speechSynthesis||!text||text.length>1200)return;const u=new SpeechSynthesisUtterance(text.replace(/[-•]\s/g,''));u.rate=1;window.speechSynthesis.cancel();window.speechSynthesis.speak(u)}
function assistantTurn(answer){const turn=el('div','turn assistant'),card=el('article','answer-card'),top=el('div','answer-top'),title=el('div','answer-title',answer.display?.title||'Hubitat MCP AI'),meta=el('div','answer-meta');const seconds=Number.isFinite(answer.elapsed_ms)?(answer.elapsed_ms/1000).toFixed(1)+'s':'';meta.appendChild(el('span','route-badge',answer.route||'unknown'));if(answer.model)meta.appendChild(el('span','route-badge',answer.model));if(seconds)meta.appendChild(el('span','route-badge',seconds));top.appendChild(title);top.appendChild(meta);card.appendChild(top);const body=el('div','answer-body');if(answer.display){body.appendChild(el('div','rich-title',answer.display.title||'Result'));if(answer.display.subtitle)body.appendChild(el('div','rich-subtitle',answer.display.subtitle));const metrics=metricGrid(answer.display.metrics);if(metrics)body.appendChild(metrics);const items=itemList(answer.display.items);if(items)body.appendChild(items);if(answer.display.note)body.appendChild(el('div','note',answer.display.note));if(answer.message&&!answer.display.items?.length&&!answer.display.metrics?.length)body.appendChild(el('div','answer-text',answer.message))}else{body.appendChild(el('div','answer-text',answer.message||answer.detail||'No response'))}const actions=el('div','answer-actions'),copy=el('button','mini','Copy');copy.onclick=()=>navigator.clipboard?.writeText(answer.message||'');actions.appendChild(copy);body.appendChild(actions);if(answer.technical){const details=el('details','tech'),summary=el('summary','', 'Technical details');details.appendChild(summary);details.appendChild(el('pre','',answer.technical));body.appendChild(details)}card.appendChild(body);turn.appendChild(card);chat.appendChild(turn);scrollChat();speakText(answer.message||'')}
async function status(){try{const r=await fetch('/api/status',{cache:'no-store'}),s=await r.json();setPill('mcp',s.mcp?.online,s.mcp?.online?`MCP online · ${s.mcp.tools||0} tools`:`MCP offline · ${s.mcp?.error||'unavailable'}`);setPill('ollama',s.ollama?.online,s.ollama?.online?`Ollama online · ${s.ollama.model}`:`Ollama offline · ${s.ollama?.error||'unavailable'}`);setPill('overall',s.mcp?.online,s.mcp?.online?'Hubitat MCP ready':'Hubitat MCP unavailable');document.getElementById('tools').textContent=s.mcp?.tools??'—';document.getElementById('model').textContent=s.ollama?.model||'—';document.getElementById('fallback').textContent=s.fallback_enabled?'Enabled':'Disabled'}catch(e){setPill('overall',false,'Status error: '+e.message)}}function setPill(id,ok,text){const node=document.getElementById(id);node.textContent='';node.appendChild(el('i','pulse'));node.appendChild(document.createTextNode(text));node.className='pill '+(ok?'online':'offline')}
function setWorking(active,started=0){working.classList.toggle('show',active);ask.disabled=active;input.disabled=active;if(!active){ask.textContent='Ask';return}ask.textContent='Working…';const elapsed=Math.floor((performance.now()-started)/1000);workingText.textContent=elapsed<2?'Contacting Hubitat…':elapsed<8?'Reading live MCP data…':'Waiting for the AI response…'}
async function submit(q){q=(q||input.value).trim();if(!q)return;input.value='';const priorHistory=history.slice(-10);userTurn(q);history.push({role:'user',content:q});save();const started=performance.now();setWorking(true,started);const timer=setInterval(()=>setWorking(true,started),1000);try{const r=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,history:priorHistory})});let answer;try{answer=await r.json()}catch{answer={success:false,message:`HTTP ${r.status}: invalid JSON response`}}if(!r.ok&&!answer.message)answer.message=answer.detail||`Request failed with HTTP ${r.status}`;assistantTurn(answer);const text=answer.message||answer.detail||'No response';history.push({role:'assistant',content:text});save();document.getElementById('lastRoute').textContent=answer.route||'—';document.getElementById('route').textContent='Route: '+(answer.route||'unknown')}catch(e){assistantTurn({success:false,route:'error',message:'Request failed: '+e.message})}finally{clearInterval(timer);setWorking(false);input.disabled=false;input.focus();status()}}
ask.onclick=()=>submit();input.addEventListener('keydown',e=>{if(e.key==='Enter')submit()});document.querySelectorAll('[data-q]').forEach(button=>button.onclick=()=>submit(button.dataset.q));document.getElementById('clear').onclick=()=>{history=[];save();chat.innerHTML='<div class="answer-card"><div class="answer-body"><div class="answer-text">Conversation cleared.</div></div></div>'};const readToggle=document.getElementById('readToggle');function refreshReadToggle(){readToggle.classList.toggle('active',readAnswers);readToggle.textContent=readAnswers?'🔊 Reading answers':'🔇 Read answers'}readToggle.onclick=()=>{readAnswers=!readAnswers;localStorage.setItem('hmcp_read_answers',String(readAnswers));refreshReadToggle()};refreshReadToggle();document.getElementById('speak').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){assistantTurn({route:'browser',message:'Speech recognition is not supported by this browser.'});return}const recognition=new SR();recognition.lang='en-GB';recognition.interimResults=false;recognition.onresult=e=>submit(e.results[0][0].transcript);recognition.onerror=e=>assistantTurn({route:'browser',message:'Speech recognition error: '+e.error});recognition.start()};status();setInterval(status,30000);input.focus();
</script>
</body>
</html>"""
    return (
        page.replace("__SAFE_TITLE__", safe_title)
        .replace("__TITLE_JSON__", title_json)
        .replace("__VERSION_JSON__", version_json)
    )
